# coding: utf-8

"""
    NetSuite REST Record API

    NetSuite REST Record API generated 2025-09-02 at 01:07:42 UTC.

    The version of the OpenAPI document: v1
    Contact: info@netsuite.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynetsuite.models.customer_contact_roles_element import CustomerContactRolesElement

class TestCustomerContactRolesElement(unittest.TestCase):
    """CustomerContactRolesElement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerContactRolesElement:
        """Test CustomerContactRolesElement
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomerContactRolesElement`
        """
        model = CustomerContactRolesElement()
        if include_optional:
            return CustomerContactRolesElement(
                links = [
                    pynetsuite.models.ns_link.nsLink(
                        rel = '', 
                        href = '', )
                    ],
                contact_name = '',
                give_access = True,
                password = '',
                password_confirm = '',
                email = '',
                ref_name = '',
                role = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                contact = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], )
            )
        else:
            return CustomerContactRolesElement(
        )
        """

    def testCustomerContactRolesElement(self):
        """Test CustomerContactRolesElement"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
