# coding: utf-8

"""
    NetSuite REST Record API

    NetSuite REST Record API generated 2025-09-01 at 22:32:31 UTC.

    The version of the OpenAPI document: v1
    Contact: info@netsuite.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynetsuite.api.credit_memo_api import CreditMemoApi


class TestCreditMemoApi(unittest.TestCase):
    """CreditMemoApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CreditMemoApi()

    def tearDown(self) -> None:
        pass

    def test_credit_memo_get(self) -> None:
        """Test case for credit_memo_get

        Get list of records.
        """
        pass

    def test_credit_memo_id_delete(self) -> None:
        """Test case for credit_memo_id_delete

        Remove record.
        """
        pass

    def test_credit_memo_id_get(self) -> None:
        """Test case for credit_memo_id_get

        Get record.
        """
        pass

    def test_credit_memo_id_patch(self) -> None:
        """Test case for credit_memo_id_patch

        Update record.
        """
        pass

    def test_credit_memo_id_put(self) -> None:
        """Test case for credit_memo_id_put

        Insert or update record.
        """
        pass

    def test_credit_memo_post(self) -> None:
        """Test case for credit_memo_post

        Insert record.
        """
        pass


if __name__ == '__main__':
    unittest.main()
