# coding: utf-8

"""
    NetSuite REST Record API

    NetSuite REST Record API generated 2025-09-01 at 22:32:31 UTC.

    The version of the OpenAPI document: v1
    Contact: info@netsuite.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynetsuite.models.credit_memo_apply_collection import CreditMemoApplyCollection

class TestCreditMemoApplyCollection(unittest.TestCase):
    """CreditMemoApplyCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreditMemoApplyCollection:
        """Test CreditMemoApplyCollection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreditMemoApplyCollection`
        """
        model = CreditMemoApplyCollection()
        if include_optional:
            return CreditMemoApplyCollection(
                links = [
                    pynetsuite.models.ns_link.nsLink(
                        rel = '', 
                        href = '', )
                    ],
                total_results = 56,
                count = 56,
                has_more = True,
                offset = 56,
                items = [
                    pynetsuite.models.credit_memo_apply_element.creditMemo-applyElement(
                        links = [
                            pynetsuite.models.ns_link.nsLink(
                                rel = '', 
                                href = '', )
                            ], 
                        total = 1.337, 
                        amount = 1.337, 
                        apply_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        ref_num = '', 
                        apply = True, 
                        due = 1.337, 
                        line = 56, 
                        created_from = '', 
                        currency = '', 
                        type = '', 
                        ref_name = '', 
                        doc = pynetsuite.models.ns_resource.nsResource(
                            id = '', 
                            ref_name = '', 
                            external_id = '', 
                            links = [
                                pynetsuite.models.ns_link.nsLink(
                                    rel = '', 
                                    href = '', )
                                ], ), )
                    ]
            )
        else:
            return CreditMemoApplyCollection(
        )
        """

    def testCreditMemoApplyCollection(self):
        """Test CreditMemoApplyCollection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
