# coding: utf-8

"""
    NetSuite REST Record API

    NetSuite REST Record API generated 2025-09-01 at 22:32:31 UTC.

    The version of the OpenAPI document: v1
    Contact: info@netsuite.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynetsuite.models.tax_type import TaxType

class TestTaxType(unittest.TestCase):
    """TaxType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TaxType:
        """Test TaxType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TaxType`
        """
        model = TaxType()
        if include_optional:
            return TaxType(
                country = pynetsuite.models.tax_type_country.taxType_country(
                    id = 'GB', 
                    ref_name = '', ),
                custom_form = pynetsuite.models.tax_type_custom_form.taxType_customForm(
                    id = '-22519', 
                    ref_name = '', ),
                name = '',
                external_id = '',
                description = '',
                id = '',
                ref_name = '',
                links = [
                    pynetsuite.models.ns_link.nsLink(
                        rel = '', 
                        href = '', )
                    ]
            )
        else:
            return TaxType(
        )
        """

    def testTaxType(self):
        """Test TaxType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
