# coding: utf-8

"""
    NetSuite REST Record API

    NetSuite REST Record API generated 2025-09-01 at 22:32:31 UTC.

    The version of the OpenAPI document: v1
    Contact: info@netsuite.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynetsuite.models.account_acct_type import AccountAcctType

class TestAccountAcctType(unittest.TestCase):
    """AccountAcctType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountAcctType:
        """Test AccountAcctType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountAcctType`
        """
        model = AccountAcctType()
        if include_optional:
            return AccountAcctType(
                id = 'NonPosting',
                ref_name = ''
            )
        else:
            return AccountAcctType(
        )
        """

    def testAccountAcctType(self):
        """Test AccountAcctType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
