# coding: utf-8

"""
    NetSuite REST Record API

    The version of the OpenAPI document: v1
    Contact: info@netsuite.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynetsuite.models.invoice_billing_address_country import InvoiceBillingAddressCountry

class TestInvoiceBillingAddressCountry(unittest.TestCase):
    """InvoiceBillingAddressCountry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvoiceBillingAddressCountry:
        """Test InvoiceBillingAddressCountry
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvoiceBillingAddressCountry`
        """
        model = InvoiceBillingAddressCountry()
        if include_optional:
            return InvoiceBillingAddressCountry(
                id = 'PR',
                ref_name = ''
            )
        else:
            return InvoiceBillingAddressCountry(
        )
        """

    def testInvoiceBillingAddressCountry(self):
        """Test InvoiceBillingAddressCountry"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
