# coding: utf-8

"""
    NetSuite REST Record API

    NetSuite REST Record API generated 2025-09-01 at 22:32:31 UTC.

    The version of the OpenAPI document: v1
    Contact: info@netsuite.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynetsuite.models.invoice_exp_cost_element_custcol_zc_item_type import InvoiceExpCostElementCustcolZcItemType

class TestInvoiceExpCostElementCustcolZcItemType(unittest.TestCase):
    """InvoiceExpCostElementCustcolZcItemType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvoiceExpCostElementCustcolZcItemType:
        """Test InvoiceExpCostElementCustcolZcItemType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvoiceExpCostElementCustcolZcItemType`
        """
        model = InvoiceExpCostElementCustcolZcItemType()
        if include_optional:
            return InvoiceExpCostElementCustcolZcItemType(
                id = 'Group',
                ref_name = ''
            )
        else:
            return InvoiceExpCostElementCustcolZcItemType(
        )
        """

    def testInvoiceExpCostElementCustcolZcItemType(self):
        """Test InvoiceExpCostElementCustcolZcItemType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
