# coding: utf-8

"""
    NetSuite REST Record API

    The version of the OpenAPI document: v1
    Contact: info@netsuite.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynetsuite.models.invoice_item_inventory_detail_inventory_assignment_collection import InvoiceItemInventoryDetailInventoryAssignmentCollection

class TestInvoiceItemInventoryDetailInventoryAssignmentCollection(unittest.TestCase):
    """InvoiceItemInventoryDetailInventoryAssignmentCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvoiceItemInventoryDetailInventoryAssignmentCollection:
        """Test InvoiceItemInventoryDetailInventoryAssignmentCollection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvoiceItemInventoryDetailInventoryAssignmentCollection`
        """
        model = InvoiceItemInventoryDetailInventoryAssignmentCollection()
        if include_optional:
            return InvoiceItemInventoryDetailInventoryAssignmentCollection(
                links = [
                    pynetsuite.models.ns_link.nsLink(
                        rel = '', 
                        href = '', )
                    ],
                total_results = 56,
                count = 56,
                has_more = True,
                offset = 56,
                items = [
                    pynetsuite.models.invoice_item_inventory_detail_inventory_assignment_element.invoice-item-inventoryDetail-inventoryAssignmentElement(
                        links = [
                            pynetsuite.models.ns_link.nsLink(
                                rel = '', 
                                href = '', )
                            ], 
                        pack_carton = '', 
                        quantity = 1.337, 
                        expiration_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        inventory_detail = 56, 
                        receipt_inventory_number = '', 
                        internal_id = 56, 
                        quantity_available = 1.337, 
                        pick_carton = '', 
                        ref_name = '', 
                        inventory_status = pynetsuite.models.ns_resource.nsResource(
                            id = '', 
                            ref_name = '', 
                            external_id = '', 
                            links = [
                                pynetsuite.models.ns_link.nsLink(
                                    rel = '', 
                                    href = '', )
                                ], ), 
                        to_inventory_status = pynetsuite.models.ns_resource.nsResource(
                            id = '', 
                            ref_name = '', 
                            external_id = '', 
                            links = , ), 
                        issue_inventory_number = , 
                        to_bin_number = , 
                        bin_number = , )
                    ]
            )
        else:
            return InvoiceItemInventoryDetailInventoryAssignmentCollection(
        )
        """

    def testInvoiceItemInventoryDetailInventoryAssignmentCollection(self):
        """Test InvoiceItemInventoryDetailInventoryAssignmentCollection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
