# coding: utf-8

"""
    NetSuite REST Record API

    NetSuite REST Record API generated 2025-09-02 at 01:07:42 UTC.

    The version of the OpenAPI document: v1
    Contact: info@netsuite.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynetsuite.models.customer_alcohol_recipient_type import CustomerAlcoholRecipientType

class TestCustomerAlcoholRecipientType(unittest.TestCase):
    """CustomerAlcoholRecipientType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerAlcoholRecipientType:
        """Test CustomerAlcoholRecipientType
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomerAlcoholRecipientType`
        """
        model = CustomerAlcoholRecipientType()
        if include_optional:
            return CustomerAlcoholRecipientType(
                id = 'CONSUMER',
                ref_name = ''
            )
        else:
            return CustomerAlcoholRecipientType(
        )
        """

    def testCustomerAlcoholRecipientType(self):
        """Test CustomerAlcoholRecipientType"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
