# coding: utf-8

"""
    NetSuite REST Record API

    NetSuite REST Record API generated 2025-09-02 at 01:07:42 UTC.

    The version of the OpenAPI document: v1
    Contact: info@netsuite.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynetsuite.models.term_collection import TermCollection

class TestTermCollection(unittest.TestCase):
    """TermCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TermCollection:
        """Test TermCollection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TermCollection`
        """
        model = TermCollection()
        if include_optional:
            return TermCollection(
                total_results = 56,
                items = [
                    pynetsuite.models.term.term(
                        is_inactive = True, 
                        discount_percent_date_driven = 1.337, 
                        last_modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        external_id = '', 
                        tname = '', 
                        discount_percent = 1.337, 
                        date_driven = pynetsuite.models.term_date_driven.term_dateDriven(
                            id = '', 
                            ref_name = '', ), 
                        due_next_month_if_within_days = 56, 
                        days_until_expiry = 56, 
                        day_of_month_net_due = 56, 
                        name = '', 
                        days_until_net_due = 56, 
                        longitemtype = '', 
                        id = '', 
                        preferred = True, 
                        day_discount_expires = 56, 
                        ref_name = '', 
                        links = [
                            pynetsuite.models.ns_link.nsLink(
                                rel = '', 
                                href = '', )
                            ], )
                    ],
                links = [
                    pynetsuite.models.ns_link.nsLink(
                        rel = '', 
                        href = '', )
                    ],
                count = 56,
                has_more = True,
                offset = 56
            )
        else:
            return TermCollection(
        )
        """

    def testTermCollection(self):
        """Test TermCollection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
