# coding: utf-8

"""
    NetSuite REST Record API

    The version of the OpenAPI document: v1
    Contact: info@netsuite.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynetsuite.models.customer_item_pricing_element import CustomerItemPricingElement

class TestCustomerItemPricingElement(unittest.TestCase):
    """CustomerItemPricingElement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerItemPricingElement:
        """Test CustomerItemPricingElement
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomerItemPricingElement`
        """
        model = CustomerItemPricingElement()
        if include_optional:
            return CustomerItemPricingElement(
                links = [
                    pynetsuite.models.ns_link.nsLink(
                        rel = '', 
                        href = '', )
                    ],
                price = 1.337,
                ref_name = '',
                currency = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                level = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                item = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], )
            )
        else:
            return CustomerItemPricingElement(
        )
        """

    def testCustomerItemPricingElement(self):
        """Test CustomerItemPricingElement"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
