# coding: utf-8

"""
    NetSuite REST Record API

    The version of the OpenAPI document: v1
    Contact: info@netsuite.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynetsuite.models.customer_contact_roles_collection import CustomerContactRolesCollection

class TestCustomerContactRolesCollection(unittest.TestCase):
    """CustomerContactRolesCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerContactRolesCollection:
        """Test CustomerContactRolesCollection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomerContactRolesCollection`
        """
        model = CustomerContactRolesCollection()
        if include_optional:
            return CustomerContactRolesCollection(
                links = [
                    pynetsuite.models.ns_link.nsLink(
                        rel = '', 
                        href = '', )
                    ],
                total_results = 56,
                count = 56,
                has_more = True,
                offset = 56,
                items = [
                    pynetsuite.models.customer_contact_roles_element.customer-contactRolesElement(
                        links = [
                            pynetsuite.models.ns_link.nsLink(
                                rel = '', 
                                href = '', )
                            ], 
                        contact_name = '', 
                        give_access = True, 
                        password = '', 
                        password_confirm = '', 
                        email = '', 
                        ref_name = '', 
                        role = pynetsuite.models.ns_resource.nsResource(
                            id = '', 
                            ref_name = '', 
                            external_id = '', 
                            links = [
                                pynetsuite.models.ns_link.nsLink(
                                    rel = '', 
                                    href = '', )
                                ], ), 
                        contact = pynetsuite.models.ns_resource.nsResource(
                            id = '', 
                            ref_name = '', 
                            external_id = '', 
                            links = , ), )
                    ]
            )
        else:
            return CustomerContactRolesCollection(
        )
        """

    def testCustomerContactRolesCollection(self):
        """Test CustomerContactRolesCollection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
