# coding: utf-8

"""
    NetSuite REST Record API

    The version of the OpenAPI document: v1
    Contact: info@netsuite.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynetsuite.models.customer_custom_form import CustomerCustomForm

class TestCustomerCustomForm(unittest.TestCase):
    """CustomerCustomForm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerCustomForm:
        """Test CustomerCustomForm
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomerCustomForm`
        """
        model = CustomerCustomForm()
        if include_optional:
            return CustomerCustomForm(
                id = '-2',
                ref_name = ''
            )
        else:
            return CustomerCustomForm(
        )
        """

    def testCustomerCustomForm(self):
        """Test CustomerCustomForm"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
