# coding: utf-8

"""
    NetSuite REST Record API

    NetSuite REST Record API generated 2025-09-01 at 22:32:31 UTC.

    The version of the OpenAPI document: v1
    Contact: info@netsuite.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynetsuite.models.invoice_accounting_book_detail_collection import InvoiceAccountingBookDetailCollection

class TestInvoiceAccountingBookDetailCollection(unittest.TestCase):
    """InvoiceAccountingBookDetailCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvoiceAccountingBookDetailCollection:
        """Test InvoiceAccountingBookDetailCollection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvoiceAccountingBookDetailCollection`
        """
        model = InvoiceAccountingBookDetailCollection()
        if include_optional:
            return InvoiceAccountingBookDetailCollection(
                links = [
                    pynetsuite.models.ns_link.nsLink(
                        rel = '', 
                        href = '', )
                    ],
                total_results = 56,
                count = 56,
                has_more = True,
                offset = 56,
                items = [
                    pynetsuite.models.invoice_accounting_book_detail_element.invoice-accountingBookDetailElement(
                        links = [
                            pynetsuite.models.ns_link.nsLink(
                                rel = '', 
                                href = '', )
                            ], 
                        exchange_rate = 1.337, 
                        ref_name = '', 
                        subsidiary = pynetsuite.models.ns_resource.nsResource(
                            id = '', 
                            ref_name = '', 
                            external_id = '', 
                            links = [
                                pynetsuite.models.ns_link.nsLink(
                                    rel = '', 
                                    href = '', )
                                ], ), 
                        accounting_book = pynetsuite.models.ns_resource.nsResource(
                            id = '', 
                            ref_name = '', 
                            external_id = '', 
                            links = , ), )
                    ]
            )
        else:
            return InvoiceAccountingBookDetailCollection(
        )
        """

    def testInvoiceAccountingBookDetailCollection(self):
        """Test InvoiceAccountingBookDetailCollection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
