# coding: utf-8

"""
    NetSuite REST Record API

    NetSuite REST Record API generated 2025-09-01 at 22:32:31 UTC.

    The version of the OpenAPI document: v1
    Contact: info@netsuite.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynetsuite.models.ns_resource_collection import NsResourceCollection

class TestNsResourceCollection(unittest.TestCase):
    """NsResourceCollection unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NsResourceCollection:
        """Test NsResourceCollection
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NsResourceCollection`
        """
        model = NsResourceCollection()
        if include_optional:
            return NsResourceCollection(
                links = [
                    pynetsuite.models.ns_link.nsLink(
                        rel = '', 
                        href = '', )
                    ],
                total_results = 56,
                items = [
                    pynetsuite.models.ns_resource.nsResource(
                        id = '', 
                        ref_name = '', 
                        external_id = '', 
                        links = [
                            pynetsuite.models.ns_link.nsLink(
                                rel = '', 
                                href = '', )
                            ], )
                    ],
                count = 56,
                has_more = True,
                offset = 56
            )
        else:
            return NsResourceCollection(
        )
        """

    def testNsResourceCollection(self):
        """Test NsResourceCollection"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
