# coding: utf-8

"""
    NetSuite REST Record API

    NetSuite REST Record API generated 2025-09-01 at 22:32:31 UTC.

    The version of the OpenAPI document: v1
    Contact: info@netsuite.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynetsuite.models.vendor import Vendor

class TestVendor(unittest.TestCase):
    """Vendor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Vendor:
        """Test Vendor
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Vendor`
        """
        model = Vendor()
        if include_optional:
            return Vendor(
                is_job_resource_vend = True,
                custentity_erpff_p2p_party_endpoint_id = '',
                custentity_bb1_cis_cisenabled = True,
                custentity_bb1_cis_ni_ref = '',
                email_transactions = True,
                custentity_zc_3wm_exclude_from_3wm = True,
                password = '',
                custentity_vl_team_size = 1.337,
                custentity_ff_sc_iban = '',
                custentity_zc_qty_tlrnce_percentage = 1.337,
                balance = 1.337,
                custentity_zc_amt_tlrnce_amount = 1.337,
                print_on_check_as = '',
                custentity_eff_nsp2p_lastrec_vatnumber = '',
                id = '',
                fax = '',
                custentity_eff_nsp2p_currency_code = '',
                custentity_ff_sc_ent_diff_pref_cust_id = '',
                unbilled_orders_primary = 1.337,
                custentity_erpff_p2p_party_endp_sch_id = '',
                custentity_vl_emergency_contact_person = '',
                custentity_zc_rate_tlrnce_percentage = 1.337,
                date_created = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                last_name = '',
                receipt_quantity_diff = 1.337,
                phone = '',
                require_pwd_change = True,
                company_name = '',
                custentitypayeeaccountaddress = '',
                custentity_eff_nsp2p_lastrec_iban = '',
                custentity_vl_public_liability_expiry = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                custentity_erpff_p2p_party_endp_op_id = '',
                custentity_ff_sc_entity_ita_apy_code = '',
                default_address = '',
                opening_balance = 1.337,
                custentity_rss_website = '',
                custentity_vl_capacity_install_per_month = 1.337,
                custentity_vl_trading_postcode = '',
                custentity_bb1_cis_worksref = '',
                is_person = True,
                custentity_zc_amt_tlrnce_percentage = 1.337,
                password2 = '',
                custentity_zc_disable_ai_fld_pop = True,
                email = '',
                opening_balance_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                custentity_tax_contact_last = '',
                custentity_nx_labor_cost = 1.337,
                custentity_vl_employers_liability_expiry = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                custentity_ff_sc_bank_code = '',
                url = '',
                custentity_vl_registered_address = '',
                custom_form = pynetsuite.models.vendor_custom_form.vendor_customForm(
                    id = '81', 
                    ref_name = '', ),
                custentity_vl_site_allocation = '',
                auto_name = True,
                custentity_eff_nsp2p_lastrec_compname = '',
                custentitypayeeaccountname = '',
                custentity_ff_sc_dis_lin_rec = True,
                custentity_tax_contact_middle = '',
                custentity_eff_nsp2p_einvoice_number = '',
                custentity_vl_trading_address = '',
                custentitypayeesortcode = '',
                custentity_vl_profl_indemnity_expiry = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(),
                external_id = '',
                custentity_erpff_p2p_basw_tax_id = '',
                entity_id = '',
                email_preference = pynetsuite.models.vendor_email_preference.vendor_emailPreference(
                    id = 'PDF', 
                    ref_name = '', ),
                subsidiary_edition = '',
                custentity_ff_sc_clickdata = '',
                custentity_bb1_missingrecord = True,
                purchase_order_amount = 1.337,
                is_autogenerated_representing_entity = True,
                receipt_quantity = 1.337,
                custentity_zc_rate_tlrnce_amount = 1.337,
                custentity_bb1_cis_hmrc_verification = '',
                mobile_phone = '',
                balance_primary = 1.337,
                custentity_zc_po_required = True,
                unbilled_orders = 1.337,
                custentity_eff_nsp2p_autoproc_billscreds = True,
                custentity_ff_sc_field_block_mapping = '',
                alt_phone = '',
                custentity_zc_qty_tlrnce_amount = 1.337,
                custentity_bb1_cis_utr = '',
                fax_transactions = True,
                custentity_rss_linkedin = '',
                custentity_vl_average_lead_time_on_goods = 56,
                alt_email = '',
                purchase_order_quantity_diff = 1.337,
                custentity_tax_contact_first = '',
                salutation = '',
                custentity_bb1_cis_hmrc_country = '',
                is_inactive = True,
                first_name = '',
                home_phone = '',
                legal_name = '',
                title = '',
                custentity_vl_trade_type_other = '',
                labor_cost = 1.337,
                give_access = True,
                default_shipping_address = '',
                custentity_rss_yoe = 1.337,
                purchase_order_quantity = 1.337,
                custentity_bb1_cis_crn = '',
                custentity_vl_pli_amount = '',
                custentity_eff_nsp2p_lastrec_cocnumber = '',
                comments = '',
                account_number = '',
                last_modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                middle_name = '',
                custentitypayeeaccountnumber = '',
                print_transactions = True,
                receipt_amount = 1.337,
                custentity_eff_nsp2p_procb2btran_aftersv = True,
                custentity_ff_sc_bank_account_number = '',
                custentity_erpff_p2p_basw_tax_scheme_id = '',
                send_email = True,
                credit_limit = 1.337,
                ref_name = '',
                links = [
                    pynetsuite.models.ns_link.nsLink(
                        rel = '', 
                        href = '', )
                    ],
                default_vendor_payment_account = pynetsuite.models.account.account(
                    is_inactive = True, 
                    is_summary = True, 
                    s_bank_name = '', 
                    opening_balance = 1.337, 
                    tran_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    external_id = '', 
                    s_bank_routing_number = '', 
                    description = '', 
                    eliminate = True, 
                    inventory = True, 
                    custrecord_ff_sc_acc_srvc_for_taxation = True, 
                    revalue = True, 
                    s_bank_company_id = '', 
                    acct_number = '', 
                    cur_doc_num = 56, 
                    s_spec_acct = pynetsuite.models.account_s_spec_acct.account_sSpecAcct(
                        id = 'CommPay', 
                        ref_name = '', ), 
                    id = '', 
                    account_search_display_name_copy = '', 
                    last_modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    general_rate = pynetsuite.models.account_general_rate.account_generalRate(
                        id = 'AVERAGE', 
                        ref_name = '', ), 
                    cash_flow_rate = pynetsuite.models.account_general_rate.account_generalRate(
                        id = 'AVERAGE', 
                        ref_name = '', ), 
                    acct_type = pynetsuite.models.account_acct_type.account_acctType(
                        id = 'NonPosting', 
                        ref_name = '', ), 
                    include_children = True, 
                    account_search_display_name = '', 
                    unit = '', 
                    display_name_with_hierarchy = '', 
                    reconcile_with_matching = True, 
                    full_name = '', 
                    acct_name = '', 
                    ref_name = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], 
                    subsidiary = pynetsuite.models.ns_resource_collection.nsResourceCollection(
                        links = [
                            pynetsuite.models.ns_link.nsLink(
                                rel = '', 
                                href = '', )
                            ], 
                        total_results = 56, 
                        items = [
                            pynetsuite.models.ns_resource.nsResource(
                                id = '', 
                                ref_name = '', 
                                external_id = '', 
                                links = , )
                            ], 
                        count = 56, 
                        has_more = True, 
                        offset = 56, ), 
                    deferral_acct = pynetsuite.models.account.account(
                        is_inactive = True, 
                        is_summary = True, 
                        s_bank_name = '', 
                        opening_balance = 1.337, 
                        tran_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        external_id = '', 
                        s_bank_routing_number = '', 
                        description = '', 
                        eliminate = True, 
                        inventory = True, 
                        custrecord_ff_sc_acc_srvc_for_taxation = True, 
                        revalue = True, 
                        s_bank_company_id = '', 
                        acct_number = '', 
                        cur_doc_num = 56, 
                        id = '', 
                        account_search_display_name_copy = '', 
                        last_modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        include_children = True, 
                        account_search_display_name = '', 
                        unit = '', 
                        display_name_with_hierarchy = '', 
                        reconcile_with_matching = True, 
                        full_name = '', 
                        acct_name = '', 
                        ref_name = '', 
                        links = , 
                        location = pynetsuite.models.ns_resource.nsResource(
                            id = '', 
                            ref_name = '', 
                            external_id = '', 
                            links = , ), 
                        billable_expenses_acct = , 
                        department = , 
                        units_type = , 
                        currency = pynetsuite.models.currency.currency(
                            is_inactive = True, 
                            symbol = '', 
                            is_anchor_currency = True, 
                            include_in_fx_rate_updates = True, 
                            last_modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            exchange_rate = 1.337, 
                            external_id = '', 
                            is_base_currency = True, 
                            locale = pynetsuite.models.currency_locale.currency_locale(
                                id = 'it_CH', 
                                ref_name = '', ), 
                            fx_rate_update_timezone = pynetsuite.models.currency_fx_rate_update_timezone.currency_fxRateUpdateTimezone(
                                id = '1', 
                                ref_name = '', ), 
                            override_currency_format = True, 
                            format_sample = '', 
                            currency_precision = 56, 
                            name = '', 
                            id = '', 
                            symbol_placement = pynetsuite.models.currency_symbol_placement.currency_symbolPlacement(
                                id = '1', 
                                ref_name = '', ), 
                            display_symbol = '', 
                            ref_name = '', 
                            links = , ), 
                        class = , 
                        account_context_search = pynetsuite.models.account_account_context_search_collection.account-accountContextSearchCollection(
                            links = , 
                            total_results = 56, 
                            count = 56, 
                            has_more = True, 
                            offset = 56, ), 
                        localizations = pynetsuite.models.account_localizations_collection.account-localizationsCollection(
                            links = , 
                            total_results = 56, 
                            count = 56, 
                            has_more = True, 
                            offset = 56, ), 
                        category1099_misc = , 
                        parent = , ), 
                    location = , 
                    billable_expenses_acct = , 
                    department = , 
                    units_type = , 
                    currency = pynetsuite.models.currency.currency(
                        is_inactive = True, 
                        symbol = '', 
                        is_anchor_currency = True, 
                        include_in_fx_rate_updates = True, 
                        last_modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        exchange_rate = 1.337, 
                        external_id = '', 
                        is_base_currency = True, 
                        override_currency_format = True, 
                        format_sample = '', 
                        currency_precision = 56, 
                        name = '', 
                        id = '', 
                        display_symbol = '', 
                        ref_name = '', 
                        links = , ), 
                    class = , 
                    account_context_search = pynetsuite.models.account_account_context_search_collection.account-accountContextSearchCollection(
                        links = , 
                        total_results = 56, 
                        count = 56, 
                        has_more = True, 
                        offset = 56, ), 
                    localizations = pynetsuite.models.account_localizations_collection.account-localizationsCollection(
                        links = , 
                        total_results = 56, 
                        count = 56, 
                        has_more = True, 
                        offset = 56, ), 
                    category1099_misc = , 
                    parent = , ),
                custentity_zc_3wm_tlrnce_type_qty = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                currency_list = pynetsuite.models.vendor_currency_list_collection.vendor-currencyListCollection(
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], 
                    total_results = 56, 
                    count = 56, 
                    has_more = True, 
                    offset = 56, 
                    items = [
                        pynetsuite.models.vendor_currency_list_element.vendor-currencyListElement(
                            links = [
                                pynetsuite.models.ns_link.nsLink(
                                    rel = '', 
                                    href = '', )
                                ], 
                            balance = 1.337, 
                            unbilled_orders = 1.337, 
                            ref_name = '', 
                            currency = pynetsuite.models.currency.currency(
                                is_inactive = True, 
                                symbol = '', 
                                is_anchor_currency = True, 
                                include_in_fx_rate_updates = True, 
                                last_modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                exchange_rate = 1.337, 
                                external_id = '', 
                                is_base_currency = True, 
                                locale = pynetsuite.models.currency_locale.currency_locale(
                                    id = 'it_CH', 
                                    ref_name = '', ), 
                                fx_rate_update_timezone = pynetsuite.models.currency_fx_rate_update_timezone.currency_fxRateUpdateTimezone(
                                    id = '1', 
                                    ref_name = '', ), 
                                override_currency_format = True, 
                                format_sample = '', 
                                currency_precision = 56, 
                                name = '', 
                                id = '', 
                                symbol_placement = pynetsuite.models.currency_symbol_placement.currency_symbolPlacement(
                                    id = '1', 
                                    ref_name = '', ), 
                                display_symbol = '', 
                                ref_name = '', 
                                links = , ), )
                        ], ),
                custentity_zc_3wm_tlrnce_type_rate = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                roles = pynetsuite.models.vendor_roles_collection.vendor-rolesCollection(
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], 
                    total_results = 56, 
                    count = 56, 
                    has_more = True, 
                    offset = 56, 
                    items = [
                        pynetsuite.models.vendor_roles_element.vendor-rolesElement(
                            links = [
                                pynetsuite.models.ns_link.nsLink(
                                    rel = '', 
                                    href = '', )
                                ], 
                            sso_only = '', 
                            ws_only = '', 
                            master_role = 56, 
                            deviceid_only = '', 
                            billing_warn = '', 
                            center_type = '', 
                            ref_name = '', 
                            selected_role = pynetsuite.models.ns_resource.nsResource(
                                id = '', 
                                ref_name = '', 
                                external_id = '', 
                                links = , ), )
                        ], ),
                contact_list = pynetsuite.models.ns_resource_collection.nsResourceCollection(
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], 
                    total_results = 56, 
                    items = [
                        pynetsuite.models.ns_resource.nsResource(
                            id = '', 
                            ref_name = '', 
                            external_id = '', 
                            links = [
                                pynetsuite.models.ns_link.nsLink(
                                    rel = '', 
                                    href = '', )
                                ], )
                        ], 
                    count = 56, 
                    has_more = True, 
                    offset = 56, ),
                custentity_zc_prevailing_quantity = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                custentity_zc_autoprocessing_preferences = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                currency = pynetsuite.models.currency.currency(
                    is_inactive = True, 
                    symbol = '', 
                    is_anchor_currency = True, 
                    include_in_fx_rate_updates = True, 
                    last_modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    exchange_rate = 1.337, 
                    external_id = '', 
                    is_base_currency = True, 
                    locale = pynetsuite.models.currency_locale.currency_locale(
                        id = 'it_CH', 
                        ref_name = '', ), 
                    fx_rate_update_timezone = pynetsuite.models.currency_fx_rate_update_timezone.currency_fxRateUpdateTimezone(
                        id = '1', 
                        ref_name = '', ), 
                    override_currency_format = True, 
                    format_sample = '', 
                    currency_precision = 56, 
                    name = '', 
                    id = '', 
                    symbol_placement = pynetsuite.models.currency_symbol_placement.currency_symbolPlacement(
                        id = '1', 
                        ref_name = '', ), 
                    display_symbol = '', 
                    ref_name = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                custentity_zc_ap_payment_schedule = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                opening_balance_account = pynetsuite.models.account.account(
                    is_inactive = True, 
                    is_summary = True, 
                    s_bank_name = '', 
                    opening_balance = 1.337, 
                    tran_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    external_id = '', 
                    s_bank_routing_number = '', 
                    description = '', 
                    eliminate = True, 
                    inventory = True, 
                    custrecord_ff_sc_acc_srvc_for_taxation = True, 
                    revalue = True, 
                    s_bank_company_id = '', 
                    acct_number = '', 
                    cur_doc_num = 56, 
                    s_spec_acct = pynetsuite.models.account_s_spec_acct.account_sSpecAcct(
                        id = 'CommPay', 
                        ref_name = '', ), 
                    id = '', 
                    account_search_display_name_copy = '', 
                    last_modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    general_rate = pynetsuite.models.account_general_rate.account_generalRate(
                        id = 'AVERAGE', 
                        ref_name = '', ), 
                    cash_flow_rate = pynetsuite.models.account_general_rate.account_generalRate(
                        id = 'AVERAGE', 
                        ref_name = '', ), 
                    acct_type = pynetsuite.models.account_acct_type.account_acctType(
                        id = 'NonPosting', 
                        ref_name = '', ), 
                    include_children = True, 
                    account_search_display_name = '', 
                    unit = '', 
                    display_name_with_hierarchy = '', 
                    reconcile_with_matching = True, 
                    full_name = '', 
                    acct_name = '', 
                    ref_name = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], 
                    subsidiary = pynetsuite.models.ns_resource_collection.nsResourceCollection(
                        links = [
                            pynetsuite.models.ns_link.nsLink(
                                rel = '', 
                                href = '', )
                            ], 
                        total_results = 56, 
                        items = [
                            pynetsuite.models.ns_resource.nsResource(
                                id = '', 
                                ref_name = '', 
                                external_id = '', 
                                links = , )
                            ], 
                        count = 56, 
                        has_more = True, 
                        offset = 56, ), 
                    deferral_acct = pynetsuite.models.account.account(
                        is_inactive = True, 
                        is_summary = True, 
                        s_bank_name = '', 
                        opening_balance = 1.337, 
                        tran_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        external_id = '', 
                        s_bank_routing_number = '', 
                        description = '', 
                        eliminate = True, 
                        inventory = True, 
                        custrecord_ff_sc_acc_srvc_for_taxation = True, 
                        revalue = True, 
                        s_bank_company_id = '', 
                        acct_number = '', 
                        cur_doc_num = 56, 
                        id = '', 
                        account_search_display_name_copy = '', 
                        last_modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        include_children = True, 
                        account_search_display_name = '', 
                        unit = '', 
                        display_name_with_hierarchy = '', 
                        reconcile_with_matching = True, 
                        full_name = '', 
                        acct_name = '', 
                        ref_name = '', 
                        links = , 
                        location = pynetsuite.models.ns_resource.nsResource(
                            id = '', 
                            ref_name = '', 
                            external_id = '', 
                            links = , ), 
                        billable_expenses_acct = , 
                        department = , 
                        units_type = , 
                        currency = pynetsuite.models.currency.currency(
                            is_inactive = True, 
                            symbol = '', 
                            is_anchor_currency = True, 
                            include_in_fx_rate_updates = True, 
                            last_modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            exchange_rate = 1.337, 
                            external_id = '', 
                            is_base_currency = True, 
                            locale = pynetsuite.models.currency_locale.currency_locale(
                                id = 'it_CH', 
                                ref_name = '', ), 
                            fx_rate_update_timezone = pynetsuite.models.currency_fx_rate_update_timezone.currency_fxRateUpdateTimezone(
                                id = '1', 
                                ref_name = '', ), 
                            override_currency_format = True, 
                            format_sample = '', 
                            currency_precision = 56, 
                            name = '', 
                            id = '', 
                            symbol_placement = pynetsuite.models.currency_symbol_placement.currency_symbolPlacement(
                                id = '1', 
                                ref_name = '', ), 
                            display_symbol = '', 
                            ref_name = '', 
                            links = , ), 
                        class = , 
                        account_context_search = pynetsuite.models.account_account_context_search_collection.account-accountContextSearchCollection(
                            links = , 
                            total_results = 56, 
                            count = 56, 
                            has_more = True, 
                            offset = 56, ), 
                        localizations = pynetsuite.models.account_localizations_collection.account-localizationsCollection(
                            links = , 
                            total_results = 56, 
                            count = 56, 
                            has_more = True, 
                            offset = 56, ), 
                        category1099_misc = , 
                        parent = , ), 
                    location = , 
                    billable_expenses_acct = , 
                    department = , 
                    units_type = , 
                    currency = pynetsuite.models.currency.currency(
                        is_inactive = True, 
                        symbol = '', 
                        is_anchor_currency = True, 
                        include_in_fx_rate_updates = True, 
                        last_modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        exchange_rate = 1.337, 
                        external_id = '', 
                        is_base_currency = True, 
                        override_currency_format = True, 
                        format_sample = '', 
                        currency_precision = 56, 
                        name = '', 
                        id = '', 
                        display_symbol = '', 
                        ref_name = '', 
                        links = , ), 
                    class = , 
                    account_context_search = pynetsuite.models.account_account_context_search_collection.account-accountContextSearchCollection(
                        links = , 
                        total_results = 56, 
                        count = 56, 
                        has_more = True, 
                        offset = 56, ), 
                    localizations = pynetsuite.models.account_localizations_collection.account-localizationsCollection(
                        links = , 
                        total_results = 56, 
                        count = 56, 
                        has_more = True, 
                        offset = 56, ), 
                    category1099_misc = , 
                    parent = , ),
                custentity_nx_location = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                custentity_vl_trade_type = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                subsidiary = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                custentity_zc_ap_primary_beneficiary_acc = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                custentity_erpff_p2p_party_endp_scheme = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                rates = pynetsuite.models.vendor_rates_collection.vendor-ratesCollection(
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], 
                    total_results = 56, 
                    count = 56, 
                    has_more = True, 
                    offset = 56, 
                    items = [
                        pynetsuite.models.vendor_rates_element.vendor-ratesElement(
                            links = [
                                pynetsuite.models.ns_link.nsLink(
                                    rel = '', 
                                    href = '', )
                                ], 
                            rate = 1.337, 
                            ref_name = '', 
                            entity_currency = pynetsuite.models.currency.currency(
                                is_inactive = True, 
                                symbol = '', 
                                is_anchor_currency = True, 
                                include_in_fx_rate_updates = True, 
                                last_modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                exchange_rate = 1.337, 
                                external_id = '', 
                                is_base_currency = True, 
                                locale = pynetsuite.models.currency_locale.currency_locale(
                                    id = 'it_CH', 
                                    ref_name = '', ), 
                                fx_rate_update_timezone = pynetsuite.models.currency_fx_rate_update_timezone.currency_fxRateUpdateTimezone(
                                    id = '1', 
                                    ref_name = '', ), 
                                override_currency_format = True, 
                                format_sample = '', 
                                currency_precision = 56, 
                                name = '', 
                                id = '', 
                                symbol_placement = pynetsuite.models.currency_symbol_placement.currency_symbolPlacement(
                                    id = '1', 
                                    ref_name = '', ), 
                                display_symbol = '', 
                                ref_name = '', 
                                links = , ), )
                        ], ),
                payables_account = pynetsuite.models.account.account(
                    is_inactive = True, 
                    is_summary = True, 
                    s_bank_name = '', 
                    opening_balance = 1.337, 
                    tran_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    external_id = '', 
                    s_bank_routing_number = '', 
                    description = '', 
                    eliminate = True, 
                    inventory = True, 
                    custrecord_ff_sc_acc_srvc_for_taxation = True, 
                    revalue = True, 
                    s_bank_company_id = '', 
                    acct_number = '', 
                    cur_doc_num = 56, 
                    s_spec_acct = pynetsuite.models.account_s_spec_acct.account_sSpecAcct(
                        id = 'CommPay', 
                        ref_name = '', ), 
                    id = '', 
                    account_search_display_name_copy = '', 
                    last_modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    general_rate = pynetsuite.models.account_general_rate.account_generalRate(
                        id = 'AVERAGE', 
                        ref_name = '', ), 
                    cash_flow_rate = pynetsuite.models.account_general_rate.account_generalRate(
                        id = 'AVERAGE', 
                        ref_name = '', ), 
                    acct_type = pynetsuite.models.account_acct_type.account_acctType(
                        id = 'NonPosting', 
                        ref_name = '', ), 
                    include_children = True, 
                    account_search_display_name = '', 
                    unit = '', 
                    display_name_with_hierarchy = '', 
                    reconcile_with_matching = True, 
                    full_name = '', 
                    acct_name = '', 
                    ref_name = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], 
                    subsidiary = pynetsuite.models.ns_resource_collection.nsResourceCollection(
                        links = [
                            pynetsuite.models.ns_link.nsLink(
                                rel = '', 
                                href = '', )
                            ], 
                        total_results = 56, 
                        items = [
                            pynetsuite.models.ns_resource.nsResource(
                                id = '', 
                                ref_name = '', 
                                external_id = '', 
                                links = , )
                            ], 
                        count = 56, 
                        has_more = True, 
                        offset = 56, ), 
                    deferral_acct = pynetsuite.models.account.account(
                        is_inactive = True, 
                        is_summary = True, 
                        s_bank_name = '', 
                        opening_balance = 1.337, 
                        tran_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        external_id = '', 
                        s_bank_routing_number = '', 
                        description = '', 
                        eliminate = True, 
                        inventory = True, 
                        custrecord_ff_sc_acc_srvc_for_taxation = True, 
                        revalue = True, 
                        s_bank_company_id = '', 
                        acct_number = '', 
                        cur_doc_num = 56, 
                        id = '', 
                        account_search_display_name_copy = '', 
                        last_modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        include_children = True, 
                        account_search_display_name = '', 
                        unit = '', 
                        display_name_with_hierarchy = '', 
                        reconcile_with_matching = True, 
                        full_name = '', 
                        acct_name = '', 
                        ref_name = '', 
                        links = , 
                        location = pynetsuite.models.ns_resource.nsResource(
                            id = '', 
                            ref_name = '', 
                            external_id = '', 
                            links = , ), 
                        billable_expenses_acct = , 
                        department = , 
                        units_type = , 
                        currency = pynetsuite.models.currency.currency(
                            is_inactive = True, 
                            symbol = '', 
                            is_anchor_currency = True, 
                            include_in_fx_rate_updates = True, 
                            last_modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            exchange_rate = 1.337, 
                            external_id = '', 
                            is_base_currency = True, 
                            locale = pynetsuite.models.currency_locale.currency_locale(
                                id = 'it_CH', 
                                ref_name = '', ), 
                            fx_rate_update_timezone = pynetsuite.models.currency_fx_rate_update_timezone.currency_fxRateUpdateTimezone(
                                id = '1', 
                                ref_name = '', ), 
                            override_currency_format = True, 
                            format_sample = '', 
                            currency_precision = 56, 
                            name = '', 
                            id = '', 
                            symbol_placement = pynetsuite.models.currency_symbol_placement.currency_symbolPlacement(
                                id = '1', 
                                ref_name = '', ), 
                            display_symbol = '', 
                            ref_name = '', 
                            links = , ), 
                        class = , 
                        account_context_search = pynetsuite.models.account_account_context_search_collection.account-accountContextSearchCollection(
                            links = , 
                            total_results = 56, 
                            count = 56, 
                            has_more = True, 
                            offset = 56, ), 
                        localizations = pynetsuite.models.account_localizations_collection.account-localizationsCollection(
                            links = , 
                            total_results = 56, 
                            count = 56, 
                            has_more = True, 
                            offset = 56, ), 
                        category1099_misc = , 
                        parent = , ), 
                    location = , 
                    billable_expenses_acct = , 
                    department = , 
                    units_type = , 
                    currency = pynetsuite.models.currency.currency(
                        is_inactive = True, 
                        symbol = '', 
                        is_anchor_currency = True, 
                        include_in_fx_rate_updates = True, 
                        last_modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        exchange_rate = 1.337, 
                        external_id = '', 
                        is_base_currency = True, 
                        override_currency_format = True, 
                        format_sample = '', 
                        currency_precision = 56, 
                        name = '', 
                        id = '', 
                        display_symbol = '', 
                        ref_name = '', 
                        links = , ), 
                    class = , 
                    account_context_search = pynetsuite.models.account_account_context_search_collection.account-accountContextSearchCollection(
                        links = , 
                        total_results = 56, 
                        count = 56, 
                        has_more = True, 
                        offset = 56, ), 
                    localizations = pynetsuite.models.account_localizations_collection.account-localizationsCollection(
                        links = , 
                        total_results = 56, 
                        count = 56, 
                        has_more = True, 
                        offset = 56, ), 
                    category1099_misc = , 
                    parent = , ),
                custentity_eff_nsp2p_createdfrom_bill2pr = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                custentity_zc_3wm_tlrnce_type_amt = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                custentity_tax_contact = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                custentity_vl_contractor_location = pynetsuite.models.ns_resource_collection.nsResourceCollection(
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], 
                    total_results = 56, 
                    items = [
                        pynetsuite.models.ns_resource.nsResource(
                            id = '', 
                            ref_name = '', 
                            external_id = '', 
                            links = [
                                pynetsuite.models.ns_link.nsLink(
                                    rel = '', 
                                    href = '', )
                                ], )
                        ], 
                    count = 56, 
                    has_more = True, 
                    offset = 56, ),
                custentity_bb1_cis_contractor_type = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                custentity_4601_defaultwitaxcode = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                custentity_vl_main_delivery_method = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                expense_account = pynetsuite.models.account.account(
                    is_inactive = True, 
                    is_summary = True, 
                    s_bank_name = '', 
                    opening_balance = 1.337, 
                    tran_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    external_id = '', 
                    s_bank_routing_number = '', 
                    description = '', 
                    eliminate = True, 
                    inventory = True, 
                    custrecord_ff_sc_acc_srvc_for_taxation = True, 
                    revalue = True, 
                    s_bank_company_id = '', 
                    acct_number = '', 
                    cur_doc_num = 56, 
                    s_spec_acct = pynetsuite.models.account_s_spec_acct.account_sSpecAcct(
                        id = 'CommPay', 
                        ref_name = '', ), 
                    id = '', 
                    account_search_display_name_copy = '', 
                    last_modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    general_rate = pynetsuite.models.account_general_rate.account_generalRate(
                        id = 'AVERAGE', 
                        ref_name = '', ), 
                    cash_flow_rate = pynetsuite.models.account_general_rate.account_generalRate(
                        id = 'AVERAGE', 
                        ref_name = '', ), 
                    acct_type = pynetsuite.models.account_acct_type.account_acctType(
                        id = 'NonPosting', 
                        ref_name = '', ), 
                    include_children = True, 
                    account_search_display_name = '', 
                    unit = '', 
                    display_name_with_hierarchy = '', 
                    reconcile_with_matching = True, 
                    full_name = '', 
                    acct_name = '', 
                    ref_name = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], 
                    subsidiary = pynetsuite.models.ns_resource_collection.nsResourceCollection(
                        links = [
                            pynetsuite.models.ns_link.nsLink(
                                rel = '', 
                                href = '', )
                            ], 
                        total_results = 56, 
                        items = [
                            pynetsuite.models.ns_resource.nsResource(
                                id = '', 
                                ref_name = '', 
                                external_id = '', 
                                links = , )
                            ], 
                        count = 56, 
                        has_more = True, 
                        offset = 56, ), 
                    deferral_acct = pynetsuite.models.account.account(
                        is_inactive = True, 
                        is_summary = True, 
                        s_bank_name = '', 
                        opening_balance = 1.337, 
                        tran_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        external_id = '', 
                        s_bank_routing_number = '', 
                        description = '', 
                        eliminate = True, 
                        inventory = True, 
                        custrecord_ff_sc_acc_srvc_for_taxation = True, 
                        revalue = True, 
                        s_bank_company_id = '', 
                        acct_number = '', 
                        cur_doc_num = 56, 
                        id = '', 
                        account_search_display_name_copy = '', 
                        last_modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        include_children = True, 
                        account_search_display_name = '', 
                        unit = '', 
                        display_name_with_hierarchy = '', 
                        reconcile_with_matching = True, 
                        full_name = '', 
                        acct_name = '', 
                        ref_name = '', 
                        links = , 
                        location = pynetsuite.models.ns_resource.nsResource(
                            id = '', 
                            ref_name = '', 
                            external_id = '', 
                            links = , ), 
                        billable_expenses_acct = , 
                        department = , 
                        units_type = , 
                        currency = pynetsuite.models.currency.currency(
                            is_inactive = True, 
                            symbol = '', 
                            is_anchor_currency = True, 
                            include_in_fx_rate_updates = True, 
                            last_modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            exchange_rate = 1.337, 
                            external_id = '', 
                            is_base_currency = True, 
                            locale = pynetsuite.models.currency_locale.currency_locale(
                                id = 'it_CH', 
                                ref_name = '', ), 
                            fx_rate_update_timezone = pynetsuite.models.currency_fx_rate_update_timezone.currency_fxRateUpdateTimezone(
                                id = '1', 
                                ref_name = '', ), 
                            override_currency_format = True, 
                            format_sample = '', 
                            currency_precision = 56, 
                            name = '', 
                            id = '', 
                            symbol_placement = pynetsuite.models.currency_symbol_placement.currency_symbolPlacement(
                                id = '1', 
                                ref_name = '', ), 
                            display_symbol = '', 
                            ref_name = '', 
                            links = , ), 
                        class = , 
                        account_context_search = pynetsuite.models.account_account_context_search_collection.account-accountContextSearchCollection(
                            links = , 
                            total_results = 56, 
                            count = 56, 
                            has_more = True, 
                            offset = 56, ), 
                        localizations = pynetsuite.models.account_localizations_collection.account-localizationsCollection(
                            links = , 
                            total_results = 56, 
                            count = 56, 
                            has_more = True, 
                            offset = 56, ), 
                        category1099_misc = , 
                        parent = , ), 
                    location = , 
                    billable_expenses_acct = , 
                    department = , 
                    units_type = , 
                    currency = pynetsuite.models.currency.currency(
                        is_inactive = True, 
                        symbol = '', 
                        is_anchor_currency = True, 
                        include_in_fx_rate_updates = True, 
                        last_modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        exchange_rate = 1.337, 
                        external_id = '', 
                        is_base_currency = True, 
                        override_currency_format = True, 
                        format_sample = '', 
                        currency_precision = 56, 
                        name = '', 
                        id = '', 
                        display_symbol = '', 
                        ref_name = '', 
                        links = , ), 
                    class = , 
                    account_context_search = pynetsuite.models.account_account_context_search_collection.account-accountContextSearchCollection(
                        links = , 
                        total_results = 56, 
                        count = 56, 
                        has_more = True, 
                        offset = 56, ), 
                    localizations = pynetsuite.models.account_localizations_collection.account-localizationsCollection(
                        links = , 
                        total_results = 56, 
                        count = 56, 
                        has_more = True, 
                        offset = 56, ), 
                    category1099_misc = , 
                    parent = , ),
                custentity_zc_prevailing_amount = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                billing_class = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                custentity_erpff_p2p_basw_tax_scheme = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                terms = pynetsuite.models.term.term(
                    is_inactive = True, 
                    discount_percent_date_driven = 1.337, 
                    last_modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    external_id = '', 
                    tname = '', 
                    discount_percent = 1.337, 
                    date_driven = pynetsuite.models.term_date_driven.term_dateDriven(
                        id = '', 
                        ref_name = '', ), 
                    due_next_month_if_within_days = 56, 
                    days_until_expiry = 56, 
                    day_of_month_net_due = 56, 
                    name = '', 
                    days_until_net_due = 56, 
                    longitemtype = '', 
                    id = '', 
                    preferred = True, 
                    day_discount_expires = 56, 
                    ref_name = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                category = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                custentity_vl_entity_source = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                default_bank_account = pynetsuite.models.account.account(
                    is_inactive = True, 
                    is_summary = True, 
                    s_bank_name = '', 
                    opening_balance = 1.337, 
                    tran_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    external_id = '', 
                    s_bank_routing_number = '', 
                    description = '', 
                    eliminate = True, 
                    inventory = True, 
                    custrecord_ff_sc_acc_srvc_for_taxation = True, 
                    revalue = True, 
                    s_bank_company_id = '', 
                    acct_number = '', 
                    cur_doc_num = 56, 
                    s_spec_acct = pynetsuite.models.account_s_spec_acct.account_sSpecAcct(
                        id = 'CommPay', 
                        ref_name = '', ), 
                    id = '', 
                    account_search_display_name_copy = '', 
                    last_modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    general_rate = pynetsuite.models.account_general_rate.account_generalRate(
                        id = 'AVERAGE', 
                        ref_name = '', ), 
                    cash_flow_rate = pynetsuite.models.account_general_rate.account_generalRate(
                        id = 'AVERAGE', 
                        ref_name = '', ), 
                    acct_type = pynetsuite.models.account_acct_type.account_acctType(
                        id = 'NonPosting', 
                        ref_name = '', ), 
                    include_children = True, 
                    account_search_display_name = '', 
                    unit = '', 
                    display_name_with_hierarchy = '', 
                    reconcile_with_matching = True, 
                    full_name = '', 
                    acct_name = '', 
                    ref_name = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], 
                    subsidiary = pynetsuite.models.ns_resource_collection.nsResourceCollection(
                        links = [
                            pynetsuite.models.ns_link.nsLink(
                                rel = '', 
                                href = '', )
                            ], 
                        total_results = 56, 
                        items = [
                            pynetsuite.models.ns_resource.nsResource(
                                id = '', 
                                ref_name = '', 
                                external_id = '', 
                                links = , )
                            ], 
                        count = 56, 
                        has_more = True, 
                        offset = 56, ), 
                    deferral_acct = pynetsuite.models.account.account(
                        is_inactive = True, 
                        is_summary = True, 
                        s_bank_name = '', 
                        opening_balance = 1.337, 
                        tran_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                        external_id = '', 
                        s_bank_routing_number = '', 
                        description = '', 
                        eliminate = True, 
                        inventory = True, 
                        custrecord_ff_sc_acc_srvc_for_taxation = True, 
                        revalue = True, 
                        s_bank_company_id = '', 
                        acct_number = '', 
                        cur_doc_num = 56, 
                        id = '', 
                        account_search_display_name_copy = '', 
                        last_modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        include_children = True, 
                        account_search_display_name = '', 
                        unit = '', 
                        display_name_with_hierarchy = '', 
                        reconcile_with_matching = True, 
                        full_name = '', 
                        acct_name = '', 
                        ref_name = '', 
                        links = , 
                        location = pynetsuite.models.ns_resource.nsResource(
                            id = '', 
                            ref_name = '', 
                            external_id = '', 
                            links = , ), 
                        billable_expenses_acct = , 
                        department = , 
                        units_type = , 
                        currency = pynetsuite.models.currency.currency(
                            is_inactive = True, 
                            symbol = '', 
                            is_anchor_currency = True, 
                            include_in_fx_rate_updates = True, 
                            last_modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            exchange_rate = 1.337, 
                            external_id = '', 
                            is_base_currency = True, 
                            locale = pynetsuite.models.currency_locale.currency_locale(
                                id = 'it_CH', 
                                ref_name = '', ), 
                            fx_rate_update_timezone = pynetsuite.models.currency_fx_rate_update_timezone.currency_fxRateUpdateTimezone(
                                id = '1', 
                                ref_name = '', ), 
                            override_currency_format = True, 
                            format_sample = '', 
                            currency_precision = 56, 
                            name = '', 
                            id = '', 
                            symbol_placement = pynetsuite.models.currency_symbol_placement.currency_symbolPlacement(
                                id = '1', 
                                ref_name = '', ), 
                            display_symbol = '', 
                            ref_name = '', 
                            links = , ), 
                        class = , 
                        account_context_search = pynetsuite.models.account_account_context_search_collection.account-accountContextSearchCollection(
                            links = , 
                            total_results = 56, 
                            count = 56, 
                            has_more = True, 
                            offset = 56, ), 
                        localizations = pynetsuite.models.account_localizations_collection.account-localizationsCollection(
                            links = , 
                            total_results = 56, 
                            count = 56, 
                            has_more = True, 
                            offset = 56, ), 
                        category1099_misc = , 
                        parent = , ), 
                    location = , 
                    billable_expenses_acct = , 
                    department = , 
                    units_type = , 
                    currency = pynetsuite.models.currency.currency(
                        is_inactive = True, 
                        symbol = '', 
                        is_anchor_currency = True, 
                        include_in_fx_rate_updates = True, 
                        last_modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        exchange_rate = 1.337, 
                        external_id = '', 
                        is_base_currency = True, 
                        override_currency_format = True, 
                        format_sample = '', 
                        currency_precision = 56, 
                        name = '', 
                        id = '', 
                        display_symbol = '', 
                        ref_name = '', 
                        links = , ), 
                    class = , 
                    account_context_search = pynetsuite.models.account_account_context_search_collection.account-accountContextSearchCollection(
                        links = , 
                        total_results = 56, 
                        count = 56, 
                        has_more = True, 
                        offset = 56, ), 
                    localizations = pynetsuite.models.account_localizations_collection.account-localizationsCollection(
                        links = , 
                        total_results = 56, 
                        count = 56, 
                        has_more = True, 
                        offset = 56, ), 
                    category1099_misc = , 
                    parent = , ),
                custentity_vl_trade_ventro = pynetsuite.models.ns_resource_collection.nsResourceCollection(
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], 
                    total_results = 56, 
                    items = [
                        pynetsuite.models.ns_resource.nsResource(
                            id = '', 
                            ref_name = '', 
                            external_id = '', 
                            links = [
                                pynetsuite.models.ns_link.nsLink(
                                    rel = '', 
                                    href = '', )
                                ], )
                        ], 
                    count = 56, 
                    has_more = True, 
                    offset = 56, ),
                custentity_ff_sc_validation_rules = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                image = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                work_calendar = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                custentity_ff_sc_entity_ita_pay_term = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                custentity_nx_skill = pynetsuite.models.ns_resource_collection.nsResourceCollection(
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], 
                    total_results = 56, 
                    items = [
                        pynetsuite.models.ns_resource.nsResource(
                            id = '', 
                            ref_name = '', 
                            external_id = '', 
                            links = [
                                pynetsuite.models.ns_link.nsLink(
                                    rel = '', 
                                    href = '', )
                                ], )
                        ], 
                    count = 56, 
                    has_more = True, 
                    offset = 56, ),
                address_book = pynetsuite.models.vendor_address_book_collection.vendor-addressBookCollection(
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], 
                    total_results = 56, 
                    count = 56, 
                    has_more = True, 
                    offset = 56, 
                    items = [
                        pynetsuite.models.vendor_address_book_element.vendor-addressBookElement(
                            links = [
                                pynetsuite.models.ns_link.nsLink(
                                    rel = '', 
                                    href = '', )
                                ], 
                            internal_id = 56, 
                            default_billing = True, 
                            last_modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            address_book_address_text = '', 
                            default_shipping = True, 
                            label = '', 
                            id = 56, 
                            address_id = '', 
                            ref_name = '', 
                            address_book_address = pynetsuite.models.vendor_address_book_address_book_address.vendor-addressBook-addressBookAddress(
                                zip = '', 
                                country = pynetsuite.models.invoice_billing_address_country.invoice_billingAddress_country(
                                    id = 'PR', 
                                    ref_name = '', ), 
                                addr2 = '', 
                                city = '', 
                                addr1 = '', 
                                last_modified_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                addr3 = '', 
                                external_id = '', 
                                addr_phone = '', 
                                addressee = '', 
                                attention = '', 
                                override = True, 
                                state = '', 
                                addr_text = '', 
                                ref_name = '', 
                                links = , ), )
                        ], ),
                contact = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                representing_subsidiary = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                custentity_zc_prevailing_rate = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                custentity_payment_type = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                incoterm = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                custentity_eff_nsp2p_defaultitem = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                custentity_ff_sc_ent_diff_pref = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                custentity_vl_entity_type = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], )
            )
        else:
            return Vendor(
        )
        """

    def testVendor(self):
        """Test Vendor"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
