# coding: utf-8

"""
    NetSuite REST Record API

    NetSuite REST Record API generated 2025-09-02 at 01:07:42 UTC.

    The version of the OpenAPI document: v1
    Contact: info@netsuite.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynetsuite.models.invoice_accounting_book_detail_element import InvoiceAccountingBookDetailElement

class TestInvoiceAccountingBookDetailElement(unittest.TestCase):
    """InvoiceAccountingBookDetailElement unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> InvoiceAccountingBookDetailElement:
        """Test InvoiceAccountingBookDetailElement
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `InvoiceAccountingBookDetailElement`
        """
        model = InvoiceAccountingBookDetailElement()
        if include_optional:
            return InvoiceAccountingBookDetailElement(
                links = [
                    pynetsuite.models.ns_link.nsLink(
                        rel = '', 
                        href = '', )
                    ],
                exchange_rate = 1.337,
                ref_name = '',
                subsidiary = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], ),
                accounting_book = pynetsuite.models.ns_resource.nsResource(
                    id = '', 
                    ref_name = '', 
                    external_id = '', 
                    links = [
                        pynetsuite.models.ns_link.nsLink(
                            rel = '', 
                            href = '', )
                        ], )
            )
        else:
            return InvoiceAccountingBookDetailElement(
        )
        """

    def testInvoiceAccountingBookDetailElement(self):
        """Test InvoiceAccountingBookDetailElement"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
