# coding: utf-8

"""
    NetSuite REST Record API

    NetSuite REST Record API generated 2025-09-02 at 01:07:42 UTC.

    The version of the OpenAPI document: v1
    Contact: info@netsuite.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynetsuite.api.invoice_api import InvoiceApi


class TestInvoiceApi(unittest.TestCase):
    """InvoiceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = InvoiceApi()

    def tearDown(self) -> None:
        pass

    def test_invoice_get(self) -> None:
        """Test case for invoice_get

        Get list of records.
        """
        pass

    def test_invoice_id_delete(self) -> None:
        """Test case for invoice_id_delete

        Remove record.
        """
        pass

    def test_invoice_id_get(self) -> None:
        """Test case for invoice_id_get

        Get record.
        """
        pass

    def test_invoice_id_patch(self) -> None:
        """Test case for invoice_id_patch

        Update record.
        """
        pass

    def test_invoice_id_put(self) -> None:
        """Test case for invoice_id_put

        Insert or update record.
        """
        pass

    def test_invoice_id_transform_credit_memo_post(self) -> None:
        """Test case for invoice_id_transform_credit_memo_post

        Transform to creditMemo.
        """
        pass

    def test_invoice_id_transform_customer_payment_post(self) -> None:
        """Test case for invoice_id_transform_customer_payment_post

        Transform to customerPayment.
        """
        pass

    def test_invoice_id_transform_return_authorization_post(self) -> None:
        """Test case for invoice_id_transform_return_authorization_post

        Transform to returnAuthorization.
        """
        pass

    def test_invoice_post(self) -> None:
        """Test case for invoice_post

        Insert record.
        """
        pass


if __name__ == '__main__':
    unittest.main()
