# coding: utf-8

"""
    NetSuite REST Record API

    NetSuite REST Record API generated 2025-09-02 at 01:07:42 UTC.

    The version of the OpenAPI document: v1
    Contact: info@netsuite.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynetsuite.api.sales_tax_item_api import SalesTaxItemApi


class TestSalesTaxItemApi(unittest.TestCase):
    """SalesTaxItemApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SalesTaxItemApi()

    def tearDown(self) -> None:
        pass

    def test_sales_tax_item_get(self) -> None:
        """Test case for sales_tax_item_get

        Get list of records.
        """
        pass

    def test_sales_tax_item_id_delete(self) -> None:
        """Test case for sales_tax_item_id_delete

        Remove record.
        """
        pass

    def test_sales_tax_item_id_get(self) -> None:
        """Test case for sales_tax_item_id_get

        Get record.
        """
        pass

    def test_sales_tax_item_id_patch(self) -> None:
        """Test case for sales_tax_item_id_patch

        Update record.
        """
        pass

    def test_sales_tax_item_id_put(self) -> None:
        """Test case for sales_tax_item_id_put

        Insert or update record.
        """
        pass

    def test_sales_tax_item_post(self) -> None:
        """Test case for sales_tax_item_post

        Insert record.
        """
        pass


if __name__ == '__main__':
    unittest.main()
