# coding: utf-8

"""
    NetSuite REST Record API

    NetSuite REST Record API generated 2025-09-02 at 01:07:42 UTC.

    The version of the OpenAPI document: v1
    Contact: info@netsuite.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pynetsuite.models.credit_memo_custom_form import CreditMemoCustomForm

class TestCreditMemoCustomForm(unittest.TestCase):
    """CreditMemoCustomForm unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreditMemoCustomForm:
        """Test CreditMemoCustomForm
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreditMemoCustomForm`
        """
        model = CreditMemoCustomForm()
        if include_optional:
            return CreditMemoCustomForm(
                id = '187',
                ref_name = ''
            )
        else:
            return CreditMemoCustomForm(
        )
        """

    def testCreditMemoCustomForm(self):
        """Test CreditMemoCustomForm"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
