# coding: utf-8

"""
    NetSuite REST Record API

    The version of the OpenAPI document: v1
    Contact: info@netsuite.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from pynetsuite.models.invoice_item_inventory_detail_custom_form import InvoiceItemInventoryDetailCustomForm
from pynetsuite.models.ns_link import NsLink
from pynetsuite.models.ns_resource import NsResource
from pynetsuite.models.vendor_bill_item_inventory_detail_inventory_assignment_collection import VendorBillItemInventoryDetailInventoryAssignmentCollection
from typing import Optional, Set
from typing_extensions import Self

class VendorBillItemInventoryDetail(BaseModel):
    """
    VendorBillItemInventoryDetail
    """ # noqa: E501
    item_description: Optional[StrictStr] = Field(default=None, description="A more complete Description of the item.", alias="itemDescription")
    unit: Optional[StrictStr] = Field(default=None, description="If the assembly uses Units of Measure, the base units are displayed in the Units field.")
    quantity: Optional[Union[StrictFloat, StrictInt]] = Field(default=None, description="In the Quantity to Build field, enter the number of assembly items you want to build. You cannot enter a quantity that exceeds the amount displayed in the Buildable Quantity field.")
    custom_form: Optional[InvoiceItemInventoryDetailCustomForm] = Field(default=None, alias="customForm")
    external_id: Optional[StrictStr] = Field(default=None, alias="externalId")
    ref_name: Optional[StrictStr] = Field(default=None, alias="refName")
    links: Optional[List[NsLink]] = None
    to_location: Optional[NsResource] = Field(default=None, alias="toLocation")
    item: Optional[NsResource] = None
    inventory_assignment: Optional[VendorBillItemInventoryDetailInventoryAssignmentCollection] = Field(default=None, alias="inventoryAssignment")
    location: Optional[NsResource] = None
    __properties: ClassVar[List[str]] = ["itemDescription", "unit", "quantity", "customForm", "externalId", "refName", "links", "toLocation", "item", "inventoryAssignment", "location"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of VendorBillItemInventoryDetail from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "links",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of custom_form
        if self.custom_form:
            _dict['customForm'] = self.custom_form.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in links (list)
        _items = []
        if self.links:
            for _item_links in self.links:
                if _item_links:
                    _items.append(_item_links.to_dict())
            _dict['links'] = _items
        # override the default output from pydantic by calling `to_dict()` of to_location
        if self.to_location:
            _dict['toLocation'] = self.to_location.to_dict()
        # override the default output from pydantic by calling `to_dict()` of item
        if self.item:
            _dict['item'] = self.item.to_dict()
        # override the default output from pydantic by calling `to_dict()` of inventory_assignment
        if self.inventory_assignment:
            _dict['inventoryAssignment'] = self.inventory_assignment.to_dict()
        # override the default output from pydantic by calling `to_dict()` of location
        if self.location:
            _dict['location'] = self.location.to_dict()
        # set to None if item_description (nullable) is None
        # and model_fields_set contains the field
        if self.item_description is None and "item_description" in self.model_fields_set:
            _dict['itemDescription'] = None

        # set to None if unit (nullable) is None
        # and model_fields_set contains the field
        if self.unit is None and "unit" in self.model_fields_set:
            _dict['unit'] = None

        # set to None if quantity (nullable) is None
        # and model_fields_set contains the field
        if self.quantity is None and "quantity" in self.model_fields_set:
            _dict['quantity'] = None

        # set to None if external_id (nullable) is None
        # and model_fields_set contains the field
        if self.external_id is None and "external_id" in self.model_fields_set:
            _dict['externalId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of VendorBillItemInventoryDetail from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "itemDescription": obj.get("itemDescription"),
            "unit": obj.get("unit"),
            "quantity": obj.get("quantity"),
            "customForm": InvoiceItemInventoryDetailCustomForm.from_dict(obj["customForm"]) if obj.get("customForm") is not None else None,
            "externalId": obj.get("externalId"),
            "refName": obj.get("refName"),
            "links": [NsLink.from_dict(_item) for _item in obj["links"]] if obj.get("links") is not None else None,
            "toLocation": NsResource.from_dict(obj["toLocation"]) if obj.get("toLocation") is not None else None,
            "item": NsResource.from_dict(obj["item"]) if obj.get("item") is not None else None,
            "inventoryAssignment": VendorBillItemInventoryDetailInventoryAssignmentCollection.from_dict(obj["inventoryAssignment"]) if obj.get("inventoryAssignment") is not None else None,
            "location": NsResource.from_dict(obj["location"]) if obj.get("location") is not None else None
        })
        return _obj


