name: Release Please
on:
  push:
    branches:
    - main


permissions:
  actions: read # Read the metrics
  contents: write # to be able to publish a GitHub release
  issues: write # to be able to comment on released issues
  pull-requests: write # to be able to comment on released pull requests
  id-token: write # to enable use of OIDC for npm provenance / AWS

env:
  MISE_PYTHON_COMPILE: false
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
    - uses: googleapis/release-please-action@v4
      id: release
      with:
        config-file: release-please-config.json
        manifest-file: .release-please-manifest.json
        release-type: python
    outputs:
      # Root level release_created
      release_created: ${{ steps.release.outputs['release_created'] }}
      # Root level tag_name
      tag_name: ${{ steps.release.outputs['tag_name'] }}
      sha: ${{ steps.release.outputs['sha'] }}

  publish:
    name: Publishes tag to pypi
    runs-on: ubuntu-latest
    needs: release-please

    if: ${{ needs.release-please.outputs.tag_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.4.19"

      - name: Build and Publish
        run: |
          uv sync --frozen
          uv build
          uv publish